version: 2.1
setup: true
orbs:
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/asdf
  asdf: rynkowsg/asdf@dev:298f600d32e003bed4136011b12ab651a63b9ed2
  # orb info: https://circleci.com/developer/orbs/orb/circleci/orb-tools
  # changelog: https://github.com/CircleCI-Public/orb-tools-orb/releases
  orb-tools: circleci/orb-tools@12.1.0
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/rynkowsg
  rynkowsg: rynkowsg/rynkowsg@0.5.0
  # orb info: https://circleci.com/developer/orbs/orb/circleci/shellcheck
  # changelog: https://github.com/CircleCI-Public/shellcheck-orb/releases
  shellcheck: circleci/shellcheck@3.2.0

filters: &filters
  tags:
    only: /.*/

jobs:
  lint_and_format:
    executor: rynkowsg/docker_x86_cimg_base
    steps:
      - checkout
      - asdf/install: {version: 0.14.0}
      - asdf/cache_restore
      - run:
          name: asdf - add plugin
          command: |
            git config --global advice.detachedHead false
            asdf plugin add babashka https://github.com/fredZen/asdf-babashka.git
            asdf plugin add java https://github.com/halcyon/asdf-java.git
            asdf plugin add shellcheck https://github.com/luizm/asdf-shellcheck.git
            asdf plugin add shfmt https://github.com/luizm/asdf-shfmt.git
      - run:
          name: asdf - install tools
          command: |
            asdf install java
            . ~/.asdf/plugins/java/set-java-home.bash
            asdf install babashka
            asdf install shellcheck
            asdf install shfmt
            bash --version
            bb --version
            java --version
            shellcheck --version
            shfmt --version
      - asdf/cache_save
      - rynkowsg/install_sosh: {version: "v0.2.0"}
      - run: make lint
      - run: make format-check

workflows:
  lint-pack:
    jobs:
      # checks
      - lint_and_format: {filters: *filters}
      - orb-tools/lint: {filters: *filters, executor: {name: orb-tools/python, resource_class: small}}
      - orb-tools/review: {filters: *filters, executor: {name: orb-tools/default, resource_class: small}}
      - shellcheck/check: {filters: *filters}
      # continue
      - orb-tools/pack: {filters: *filters, executor: {name: orb-tools/default, resource_class: small}}
      - orb-tools/continue:
          requires:
            - lint_and_format
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters
          orb_name: gpg
          pipeline_number: <<pipeline.number>>
          vcs_type: <<pipeline.project.type>>
